### ISSUE TITLE
Структура домашнего задания

### ISSUE THREAD

**Issue by igorsimdyanov** [sfmorozov/gb.ruby#3]
Лучше домашние задания разложить по каталогам. Мы скоро будем использовать для создания программы несколько файлов и уже сейчас хорошо бы начинать структурировать свой код (в том числе подбирая хорошие названия для каталогов и программ). Это код потом будут смотреть ваши потенциальные работодатели, чем он аккуратнее оформлен, тем лучше.

**Comment by sfmorozov** [comment]
Принято
